---
title: "Extended analyses for Northwest Territories caribou range planning"
author: "Alex M. Chubaty & Tati Micheletti"
date: "2022-07-29"
output:
  pdf_document: default
editor_options:
  chunk_output_type: console
  markdown:
    wrap: sentence
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  message = FALSE,
  warning = FALSE,
  results = "hold"
)

if (file.exists(".Renviron")) readRenviron(".Renviron")

source("01a-packages-libPath.R")

if (!"Require" %in% rownames(installed.packages())) {
  remotes::install_github("PredictiveEcology/Require@development")
} else if (packageVersion("Require") < "0.1.0.9000") {
  remotes::install_github("PredictiveEcology/Require@development")
}
library("Require")

Require(c("fs", "knitr", "qs"))

data_dirs <- list(
  landscape = file.path("outputs"), ## TODO: update this
  caribou = file.path("outputs") ## TODO: update this
)
stopifnot(dir_exists(unlist(data_dirs)))
```

## Overview

<!-- TODO: provide background/context -->

- based on NWT pilot project and WBI
- updated climate projections (CIMP6)
- updated fire and vegetation models
- expanded caribou areas

All data products and modules have been developed using the PERFICT approach as outlined in McIntire _et al._ [-@mcintire_perfict_2022], which enables them to be part of update cycles as needed going forward.

## Pilot project outputs (NWT)

### Landscape simulations

Our simulation experiments were designed to contrast climate-sensitive and non-climate sensitive models for tree growth and mortality, in addition to wildfire from 2011-2100 [Table 2, @micheletti2021].
Simulations used either a climate-sensitive vegetation model (LandR.CS) or a non-climate-sensitive version (LandR), together with either a climate-sensitive wildfire model (fireSense) or a non-climate-sensitive version (SCFM).

Each simulation run produced the following files:

- decadal aboveground net primary productivity (ANPP) maps (`.rds`);
- decadal wildfire burn maps (`.rds`);
- wildfire burn summaries for years 2011, 2056, 2100 (`.rds`);
- decadal vegetation (tree only) cohort data objects (`.rds`), from which cohort age, aboveground biomass, and species composition can be extracted;
- wildfire ignition, escape, and spread model predictions for years 2011, 2056, 2100 (`.rds`);
- decadal vegetation (tree) mortality maps (`.rds`);
- decadal simulated vegetation biomass maps (`.rds`).

### Boreal Caribou simulations

We forecast suitable habitat for boreal woodland caribou (_Rangifer tarandus caribou_) across the union of NT1 herd range and BCR 6 in Northern Canada (mostly Taiga Plains region).
We also simulated demographic parameters for five geographical areas. For both models, we simulated changes across 90 years of climate-driven landscape change [described in @stewart; available [here](https://drive.google.com/file/d/1NHzLDCbfEr2x5J3eD59r7uojrE-VN1y9/)].

We have simulated landscape attributes for each caribou monitoring area (Dehcho North, Dehcho South, GSA North, GSA South, Hay River Lowlands), and each CIMP5 climate models (GCMs: CCSM4, CanESM2, INM-CM4):

- decadal mean relative selection + uncertainty RSF layers (`.rds`);
- disturbance summary at year 2100 (`.rds`).
- annual caribou population demographics table maps.

# Additional tools for analyzing simulation results

## `Biomass_summary` module

Summarizes the results of multiple LandR Biomass simulations, across multiple study areas, climate scenarios, and replicates.
Intended to be used for post-simulation processing of multiple LandR Biomass simulations, following a LandR-fS project structure and workflow described and templated in the `SpaDES.project` package.

Available from: <https://github.com/PredictiveEcology/Biomass_summary>

## `caribouMetrics` package

Implements caribou resource selection functions, as well as caribou population and demographic models.
Incorporates code form Tati's [`caribouPopGrowthModel`](https://github.com/tati-micheletti/caribouPopGrowthModel) module and is used in this module to add uncertainty due to beta distribution used to fit the original models proposed by Johnson et al. [-@johnson2020].

Available from: <https://github.com/LandSciTech/caribouMetrics> (currently a private repo)

## `fireSense_summary` module

Summarizes the results of multiple fireSense simulations, across multiple study areas, climate scenarios, and replicates.
Creates burn summary figures, historic burn summary plots, and cumulative simulated burn maps.

Available from: <https://github.com/PredictiveEcology/fireSense_summary>

## NWT `posthocFunctions` scripts

Various utilities to summarize the NWT simulation outputs and create plots for vegetation, wildfire, landbird, and caribou components.

In particular, provides scripts for producing the plots used in Micheletti et al. [-@micheletti2021]:

- <https://github.com/tati-micheletti/NWT/blob/development/posthocFunctions/!!!plotsPaper_NotFun.R>

As well as those in Stewart et al. [-@stewart]:

- <https://github.com/tati-micheletti/NWT/blob/development/posthocFunctions/!!!caribouMSPlots.R>

Available from: <https://github.com/tati-micheletti/NWT/tree/development/posthocFunctions>

## `posthocLandR` module

Post-processing module for LandR Biomass simulations.
Prepares the biomass, leading species, average forest age objects for summary across simulations.

Available from: <https://github.com/tati-micheletti/NWT/blob/development/modules/posthocLandR/posthocLandR.R>

## `usefulFuns` package

Various utilities for producing summary plots and objects, including:

- assembling the layers for the caribou RSFs and plotting them;
- various plots for vegetation biomass;
- forest age plots;
- generating and plotting burn summary maps;
- helper functions for working with bird models;
- preparing climate layers.

Available from: <https://github.com/PredictiveEcology/usefulFuns> (forked form <https://github.com/tati-micheletti/usefulFuns>)

#### NOTE:

- These `usefulFuns` repositories are not actively maintained, although a tagged version of the package used for Tati's original analyses does work with the corresponding version of the model code.
- Tati's repository is currently out of sync with the Predictive Ecology fork (both ahead and behind on several commits).

# References

<!-- autogenerated from references.bib -->
